### ISSUE TITLE
run_local wrong 

### ISSUE THREAD

**Issue by zhengkai215** [CNevd/Difacto_DMLC#19]
你好，我在运行run_local.sh脚本的时候，停在了2017-07-27 16:17:08,738 INFO start listen on 127.0.0.1:9091 这段INFO了，不知道是什么原因？

**Comment by zhengkai215** [comment]
超时后的报错：


[sshroot@alihd1_100244 linear]$ sh run_local.sh
2017-07-27 16:17:08,738 INFO start listen on 127.0.0.1:9091
F0727 16:25:32.911845 27919 manager.cc:55] Timeout (500 sec) to wait all other nodes initialized. See commmets for more information
F0727 16:25:32.919481 27924 manager.cc:55] Timeout (500 sec) to wait all other nodes initialized. See commmets for more information
*** Check failure stack trace: ***
    @           0x48f86a  google::LogMessage::Fail()
    @           0x491732  google::LogMessage::SendToLog()
*** Check failure stack trace: ***
    @           0x48f44f  google::LogMessage::Flush()
    @           0x48f86a  google::LogMessage::Fail()
    @           0x49204e  google::LogMessageFatal::~LogMessageFatal()
    @           0x491732  google::LogMessage::SendToLog()
    @           0x48f44f  google::LogMessage::Flush()
    @           0x474c42  ps::Manager::Run()
    @           0x49204e  google::LogMessageFatal::~LogMessageFatal()
    @           0x47b645  ps::Postoffice::Run()
    @           0x474c42  ps::Manager::Run()
    @           0x4254c1  main
    @           0x47b645  ps::Postoffice::Run()
    @           0x4254c1  main
F0727 16:25:32.934928 27927 manager.cc:55] Timeout (500 sec) to wait all other nodes initialized. See commmets for more information
*** Check failure stack trace: ***
    @     0x7efe8cccfd1d  __libc_start_main
    @     0x7fb2c907ed1d  __libc_start_main
    @           0x48f86a  google::LogMessage::Fail()
    @           0x491732  google::LogMessage::SendToLog()
    @           0x48f44f  google::LogMessage::Flush()
    @           0x410d11  (unknown)
    @           0x410d11  (unknown)
    @           0x49204e  google::LogMessageFatal::~LogMessageFatal()
    @           0x474c42  ps::Manager::Run()
    @           0x47b645  ps::Postoffice::Run()
    @           0x4254c1  main
    @     0x7effbee5cd1d  __libc_start_main
    @           0x410d11  (unknown)
bash: line 9: 27924 Aborted                 build/linear.dmlc guide/demo.conf
bash: line 9: 27927 Aborted                 build/linear.dmlc guide/demo.conf
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/sshroot/zhengkai/Difacto_DMLC/dmlc-core/tracker/tracker.py", line 345, in <lambda>
    self.thread = Thread(target = (lambda : subprocess.check_call(self.cmd, env=env, shell=True)), args = ())
  File "/usr/local/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'build/linear.dmlc guide/demo.conf ' returned non-zero exit status -6

[16:25:32] include/dmlc/logging.h:208: [16:25:32] src/io/local_filesys.cc:149: Check failed: allow_null  LocalFileSystem: fail to open "agaricus_model_part-0"
terminate called after throwing an instance of 'dmlc::Error'
  what():  [16:25:32] src/io/local_filesys.cc:149: Check failed: allow_null  LocalFileSystem: fail to open "agaricus_model_part-0"
run_local.sh: line 4: 32416 Aborted                 build/dump.dmlc model_in="agaricus_model_part-0" dump_out="dump.txt"
