### ISSUE TITLE
run_yarn.sh fail

### ISSUE THREAD

**Issue by everwind** [CNevd/Difacto_DMLC#22]
sh  run_yarn.sh 
the error infomation:

18/01/24 13:26:09 WARN util.NativeCodeLoader (NativeCodeLoader.java:<clinit>(62)) : Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
18/01/24 13:26:09 INFO client.RMProxy (RMProxy.java:createRMProxy(92)) : Connecting to ResourceManager at master4.osos.com/10.155.140.215:8032
18/01/24 13:26:16 INFO dmlc.Client (Client.java:run(289)) : jobname=DMLC[nworker=2,nsever=1]:difacto.dmlc,username=nlp_qrw
18/01/24 13:26:16 INFO dmlc.Client (Client.java:run(296)) : Submitting application application_1506450123858_250218
18/01/24 13:26:16 INFO impl.YarnClientImpl (YarnClientImpl.java:submitApplication(236)) : Submitted application application_1506450123858_250218
F0124 13:34:31.273530  7162 manager.cc:55] Timeout (500 sec) to wait all other nodes initialized. See commmets for more information
*** Check failure stack trace: ***
    @           0x482eaa  google::LogMessage::Fail()
    @           0x484d72  google::LogMessage::SendToLog()
    @           0x482a8f  google::LogMessage::Flush()
    @           0x48568e  google::LogMessageFatal::~LogMessageFatal()
    @           0x4715e2  ps::Manager::Run()
    @           0x468e19  ps::Postoffice::Run()
    @           0x40813b  main
    @     0x7f180e2dbb35  __libc_start_main
    @           0x40a221  (unknown)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/data1/peak/peakzeng/Difacto_DMLC-master/dmlc-core/tracker/tracker.py", line 345, in <lambda>
    self.thread = Thread(target = (lambda : subprocess.check_call(self.cmd, env=env, shell=True)), args = ())
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '../../dmlc-core/tracker/../yarn//run_hdfs_prog.py build/difacto.dmlc guide/demo_hdfs.conf ' returned non-zero exit status 250

**Comment by AriesSurfer** [comment]
hi ,hava you already solve the problem?  I met the same question.
