### ISSUE TITLE
how to fix run_yarn.sh python error

### ISSUE THREAD

**Issue by formath** [CNevd/Difacto_DMLC#3]
2016-06-30 14:44:10,301 INFO start listen on 10.32.44.171:9102
Traceback (most recent call last):
  File "../../dmlc-core/tracker/../yarn//run_hdfs_prog.py", line 47, in <module>
    ret = subprocess.call(args = sys.argv[1:], env = env)
  File "/usr/lib64/python2.6/subprocess.py", line 478, in call
    p = Popen(_popenargs, *_kwargs)
  File "/usr/lib64/python2.6/subprocess.py", line 642, in **init**
    errread, errwrite)
  File "/usr/lib64/python2.6/subprocess.py", line 1238, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.6/threading.py", line 484, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/home/formath/github/Difacto_DMLC/dmlc-core/tracker/tracker.py", line 345, in <lambda>
    self.thread = Thread(target = (lambda : subprocess.check_call(self.cmd, env=env, shell=True)), args = ())
  File "/usr/lib64/python2.6/subprocess.py", line 505, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '../../dmlc-core/tracker/../yarn//run_hdfs_prog.py build/linear.dmlc guide/demo_hdfs.conf ' returned non-zero exit status 1

**Comment by CNevd** [comment]
never have come across with python2.7, check [here](http://stackoverflow.com/questions/11142485/why-does-this-command-work-with-os-system-but-not-subprocess-popen) to see if can solve the problem

**Comment by CNevd** [comment]
@formath  did you fix this problem?
